### ISSUE TITLE
questions/suggestions

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/paint-box#49]
step 2 between line 64 and 68: The text doesn't make explicit how to actually change the costume centre. I think there are a couple of instruction missing along the lines of 'click on the costumes tab, click on this icon, move the crosshair'.

the meta.yml file doesn't seem to have a project title field?

**Comment by martinohanlon** [comment]
@MarcScott I hope you dont mind, I jumped into this.

@JaninaPi I have made some small changes to include some specific instructions in step 2 and have also added the title into the meta.yml - thanks.

https://github.com/raspberrypilearning/paint-box/commit/3c425f178b96e6313989c7d30dab7a0b50bada2b
