### ISSUE TITLE
Wrong title

### ISSUE THREAD

**Issue by tracygardner** [raspberrypilearning/paint-box#55]
https://projects.raspberrypi.org/en/projects/paint-box/4

Has navigation title Challenge: shortcut but should be Challenge: more pencils

**Comment by ninaszymor** [comment]
@tracygardner @MarcScott 

There is also a problem with step 6 - meta.yml says 'Challenge: more pencils' while the corresponding .md file says 'Challenge: keyborad commands'

https://projects.raspberrypi.org/en/projects/paint-box/6
