### ISSUE TITLE
Duplicate pencil screenshot

### ISSUE THREAD

**Issue by daraghbroderick** [raspberrypilearning/paint-box#67]
Project site feedback: "Scratch 3 Paint Box Project. In Coloured pencils section, the step to rename the pencil costume pencil-a to pencil-blue is missing. In the next step it has magically changed when making pencil-green."

Had a brief look, might be in relation to the sprite names in the first couple of screenshots in step 3.

**Comment by daraghbroderick** [comment]
This has now come up a few times -> "the step of renaming the costume to pencil-blue first has been omitted (so words and screenshot don't match)"

**Comment by MarcScott** [comment]
I've updated in draft, but currently blocked by a Spanish translation problem
